import { defineConfig, type Plugin } from "vite";
import { resolve, dirname, posix } from "node:path";
import { fileURLToPath, URL } from "node:url";
import { writeFileSync, readFileSync, readdirSync } from "node:fs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "../..");

// ── Balance-editor "Apply to source" endpoint (dev only) ───────────────
// The balance editor (balance-editor.html) edits in-memory working copies of the
// card catalog, augments, vote events, AI decks and progression constants. Its
// original workflow was "download a generated .ts file and paste it over the
// source by hand". This dev-server middleware closes that loop: POST the working
// data to /__apply-balance and it writes each change straight into the real
// source file, so the editor is the only thing the balancer has to open.
//
// It is gated to `apply: "serve"` (never ships in the static build) and only ever
// touches the five whitelisted files below, all inside the repo.

// Scan from an opening bracket to its matching close, skipping string contents so
// brackets inside card text (descriptions etc.) don't throw the depth off.
function findMatchingBracket(src: string, openIdx: number): number {
  const open = src[openIdx];
  const close = open === "[" ? "]" : "}";
  let depth = 0;
  let inStr = false;
  let quote = "";
  for (let i = openIdx; i < src.length; i++) {
    const ch = src[i];
    if (inStr) {
      if (ch === "\\") i++;
      else if (ch === quote) inStr = false;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      inStr = true;
      quote = ch;
    } else if (ch === open) {
      depth++;
    } else if (ch === close) {
      depth--;
      if (depth === 0) return i;
    }
  }
  return -1;
}

// Replace the initializer literal of `export const <name> = <open>...<close>`
// in place, preserving everything around it (doc comments, the type annotation,
// any trailing `as const`, and all the other declarations in the file).
function replaceConstInitializer(src: string, name: string, open: "[" | "{", literal: string): string {
  const decl = src.indexOf(`export const ${name}`);
  if (decl < 0) throw new Error(`could not find "export const ${name}"`);
  const eq = src.indexOf("=", decl);
  const openIdx = src.indexOf(open, eq);
  if (eq < 0 || openIdx < 0) throw new Error(`could not find initializer for ${name}`);
  const closeIdx = findMatchingBracket(src, openIdx);
  if (closeIdx < 0) throw new Error(`unbalanced ${open} in ${name}`);
  return src.slice(0, openIdx) + literal + src.slice(closeIdx + 1);
}

type BalancePayload = {
  cards?: unknown[];
  amps?: unknown[];
  votes?: unknown[];
  aiThemes?: unknown[];
  aiDecks?: Record<string, unknown>;
  progression?: { MAX_LEVEL?: number; LEVEL_UP_GOLD?: number; MAX_LEVEL_XP_REQUIREMENT?: number };
};

function applyBalanceData(payload: BalancePayload): string[] {
  const written: string[] = [];
  const json = (v: unknown) => JSON.stringify(v, null, 2);
  const editAtomic = (relPath: string, fn: (src: string) => string) => {
    const abs = resolve(repoRoot, relPath);
    writeFileSync(abs, fn(readFileSync(abs, "utf8")), "utf8");
    written.push(relPath);
  };

  if (payload.cards) {
    // catalog.generated.ts is owned entirely by the editor — rewrite it whole.
    const file =
      "// Auto-generated by balance-editor\n" +
      'import type { CardDefinition } from "./types.js";\n\n' +
      `export const CARD_CATALOG_GENERATED = ${json(payload.cards)} as const satisfies readonly CardDefinition[];\n`;
    writeFileSync(resolve(repoRoot, "packages/cards/src/catalog.generated.ts"), file, "utf8");
    written.push("packages/cards/src/catalog.generated.ts");
  }
  if (payload.amps) {
    editAtomic("packages/cards/src/amplificationDb.ts", (src) =>
      replaceConstInitializer(src, "AMPLIFICATION_DB", "[", json(payload.amps))
    );
  }
  if (payload.votes) {
    editAtomic("packages/cards/src/voteEventDb.ts", (src) =>
      replaceConstInitializer(src, "VOTE_EVENT_DB", "[", json(payload.votes))
    );
  }
  if (payload.aiThemes || payload.aiDecks) {
    editAtomic("packages/shared/src/index.ts", (src) => {
      let out = src;
      if (payload.aiThemes) out = replaceConstInitializer(out, "AI_THEMES", "[", json(payload.aiThemes));
      if (payload.aiDecks) out = replaceConstInitializer(out, "AI_THEME_DECKS", "{", json(payload.aiDecks));
      return out;
    });
  }
  if (payload.progression) {
    const p = payload.progression;
    editAtomic("packages/shared/src/progression.ts", (src) => {
      let out = src;
      const set = (name: string, val: number | undefined) => {
        if (val == null) return;
        out = out.replace(new RegExp(`export const ${name} = \\d+;`), `export const ${name} = ${val};`);
      };
      set("MAX_LEVEL", p.MAX_LEVEL);
      set("LEVEL_UP_GOLD", p.LEVEL_UP_GOLD);
      set("MAX_LEVEL_XP_REQUIREMENT", p.MAX_LEVEL_XP_REQUIREMENT);
      return out;
    });
  }
  return written;
}

function balanceApplyPlugin(): Plugin {
  return {
    name: "twcardgame-balance-apply",
    apply: "serve",
    configureServer(server) {
      server.middlewares.use("/__apply-balance", (req, res) => {
        if (req.method !== "POST") {
          res.statusCode = 405;
          res.end("POST only");
          return;
        }
        let body = "";
        req.on("data", (chunk) => (body += chunk));
        req.on("end", () => {
          res.setHeader("Content-Type", "application/json");
          try {
            const written = applyBalanceData(JSON.parse(body) as BalancePayload);
            res.end(JSON.stringify({ ok: true, written }));
          } catch (err) {
            res.statusCode = 500;
            res.end(JSON.stringify({ ok: false, error: (err as Error).message }));
          }
        });
      });
    }
  };
}

// Boot-time asset manifest (see apps/web/src/app/preloader.ts):
// scans public/ at config time and exposes a categorised list of media URLs as a
// virtual module so the client can warm every asset before showing the menu.
// Generated here (not committed) so it can never drift from the files on disk,
// and works identically in `vite dev` (public/ on disk) and the R2-backed deploy
// (same `/images /audio /video` URLs are served by the Pages Functions).
const ASSET_MANIFEST_ID = "virtual:asset-manifest";

type AssetManifest = {
  images: string[];
  audioSfx: string[];
  audioBgm: string[];
  video: string[];
};

function walkPublicFiles(root: string): string[] {
  const out: string[] = [];
  const walk = (abs: string, rel: string): void => {
    for (const entry of readdirSync(abs, { withFileTypes: true })) {
      if (entry.name.startsWith(".")) continue;
      const childAbs = resolve(abs, entry.name);
      const childRel = rel ? `${rel}/${entry.name}` : entry.name;
      if (entry.isDirectory()) walk(childAbs, childRel);
      else if (entry.isFile()) out.push(childRel);
    }
  };
  walk(root, "");
  return out;
}

// When both `<name>.webp` and a raster twin (`<name>.png/.jpg/.jpeg`) live in the
// same folder, the catalog/UI only ever references the .webp — the twins are the
// ~75MB of original uploads. Drop them from the preload set so the loading screen
// warms ~20MB instead of ~95MB of images.
function dropRedundantRasterTwins(files: string[]): string[] {
  const webpKeys = new Set(
    files.filter((f) => f.toLowerCase().endsWith(".webp")).map((f) => f.slice(0, f.lastIndexOf(".")))
  );
  return files.filter((f) => {
    const ext = posix.extname(f).toLowerCase();
    if (ext === ".png" || ext === ".jpg" || ext === ".jpeg") {
      return !webpKeys.has(f.slice(0, f.lastIndexOf(".")));
    }
    return true;
  });
}

function buildAssetManifest(): AssetManifest {
  const publicDir = resolve(__dirname, "public");
  let files: string[];
  try {
    files = walkPublicFiles(publicDir).map((f) => `/${f}`);
  } catch {
    return { images: [], audioSfx: [], audioBgm: [], video: [] };
  }
  const images = dropRedundantRasterTwins(files.filter((f) => f.startsWith("/images/")));
  const standaloneImage = files.filter((f) => /^\/[^/]+\.(webp|png|jpg|jpeg|svg)$/i.test(f));
  return {
    images: [...images, ...standaloneImage].sort(),
    audioSfx: files.filter((f) => f.startsWith("/audio/sfx/")).sort(),
    audioBgm: files.filter((f) => f.startsWith("/audio/bgm/")).sort(),
    video: files.filter((f) => f.startsWith("/video/")).sort()
  };
}

function assetManifestPlugin(): Plugin {
  const resolved = `\0${ASSET_MANIFEST_ID}`;
  return {
    name: "twcardgame-asset-manifest",
    resolveId(id) {
      return id === ASSET_MANIFEST_ID ? resolved : undefined;
    },
    load(id) {
      if (id !== resolved) return undefined;
      return `export const assetManifest = ${JSON.stringify(buildAssetManifest())};\n`;
    }
  };
}

// Cloudflare Pages control files emitted into the build output (Phase 4):
// - _routes.json scopes Functions to the R2-backed media prefixes ONLY, so every
//   HTML/JS/CSS request is served as a plain static asset (zero function calls).
// - _headers gives Vite's content-hashed bundle long-lived immutable caching.
// They are generated here (rather than committed under public/) because the build
// no longer copies public/ — the media live in R2, not in the Pages deploy.
const ASSET_PREFIXES = ["/images/*", "/audio/*", "/video/*"];

function cloudflarePagesFiles(): Plugin {
  return {
    name: "twcardgame-cloudflare-pages-files",
    apply: "build",
    closeBundle() {
      const outDir = resolve(__dirname, "dist-public");
      writeFileSync(
        resolve(outDir, "_routes.json"),
        JSON.stringify({ version: 1, include: ASSET_PREFIXES, exclude: [] }, null, 2) + "\n"
      );
      writeFileSync(
        resolve(outDir, "_headers"),
        ["/assets/*", "  Cache-Control: public, max-age=31536000, immutable", ""].join("\n")
      );
    }
  };
}

export default defineConfig({
  publicDir: "public",
  plugins: [cloudflarePagesFiles(), assetManifestPlugin(), balanceApplyPlugin()],
  resolve: {
    alias: [
      {
        find: /^buffer$/,
        replacement: fileURLToPath(new URL("../../node_modules/buffer/index.js", import.meta.url))
      }
    ],
    conditions: ["source"]
  },
  server: {
    port: 5173
  },
  build: {
    outDir: "dist-public",
    // Media (129MB across images/audio/video) is served from R2 by the Pages
    // Functions, so it must NOT be copied into the static deploy. The dev server
    // still serves public/ from disk, so local play is unaffected.
    copyPublicDir: false,
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        "balance-editor": resolve(__dirname, "balance-editor.html")
      }
    }
  },
  esbuild: {
    useDefineForClassFields: false
  }
});
